package www.zhizunbao.dto.insure;

import java.io.Serializable;

@SuppressWarnings("serial")
public class Img  implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column img.img_id
     *
     * @mbggenerated Sun Apr 15 19:18:04 CST 2018
     */
    private Integer imgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column img.img_src
     *
     * @mbggenerated Sun Apr 15 19:18:04 CST 2018
     */
    private String imgSrc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column img.img_alt
     *
     * @mbggenerated Sun Apr 15 19:18:04 CST 2018
     */
    private String imgAlt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column img.img_id
     *
     * @return the value of img.img_id
     *
     * @mbggenerated Sun Apr 15 19:18:04 CST 2018
     */
    public Integer getImgId() {
        return imgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column img.img_id
     *
     * @param imgId the value for img.img_id
     *
     * @mbggenerated Sun Apr 15 19:18:04 CST 2018
     */
    public void setImgId(Integer imgId) {
        this.imgId = imgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column img.img_src
     *
     * @return the value of img.img_src
     *
     * @mbggenerated Sun Apr 15 19:18:04 CST 2018
     */
    public String getImgSrc() {
        return imgSrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column img.img_src
     *
     * @param imgSrc the value for img.img_src
     *
     * @mbggenerated Sun Apr 15 19:18:04 CST 2018
     */
    public void setImgSrc(String imgSrc) {
        this.imgSrc = imgSrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column img.img_alt
     *
     * @return the value of img.img_alt
     *
     * @mbggenerated Sun Apr 15 19:18:04 CST 2018
     */
    public String getImgAlt() {
        return imgAlt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column img.img_alt
     *
     * @param imgAlt the value for img.img_alt
     *
     * @mbggenerated Sun Apr 15 19:18:04 CST 2018
     */
    public void setImgAlt(String imgAlt) {
        this.imgAlt = imgAlt;
    }
}