package www.zhizunbao.mapper.insure;

import java.util.List;

import www.zhizunbao.dto.insure.Feature;

public interface FeatureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feature
     *
     * @mbggenerated Sun Apr 15 19:21:19 CST 2018
     */
    int deleteByPrimaryKey(Integer featureId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feature
     *
     * @mbggenerated Sun Apr 15 19:21:19 CST 2018
     */
    int insert(Feature record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feature
     *
     * @mbggenerated Sun Apr 15 19:21:19 CST 2018
     */
    int insertSelective(Feature record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feature
     *
     * @mbggenerated Sun Apr 15 19:21:19 CST 2018
     */
    Feature selectByPrimaryKey(Integer featureId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feature
     *
     * @mbggenerated Sun Apr 15 19:21:19 CST 2018
     */
    int updateByPrimaryKeySelective(Feature record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feature
     *
     * @mbggenerated Sun Apr 15 19:21:19 CST 2018
     */
    int updateByPrimaryKey(Feature record);

	List<Feature> findFeatureList();

	List<Feature> findFeatureListByInsureId(Integer insureId);
}