package www.zhizunbao.mapper.activity;

import java.util.List;

import www.zhizunbao.dto.activity.Discounts;

public interface DiscountsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discounts
     *
     * @mbggenerated Fri Apr 27 22:28:05 CST 2018
     */
    int deleteByPrimaryKey(Integer disId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discounts
     *
     * @mbggenerated Fri Apr 27 22:28:05 CST 2018
     */
    int insert(Discounts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discounts
     *
     * @mbggenerated Fri Apr 27 22:28:05 CST 2018
     */
    int insertSelective(Discounts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discounts
     *
     * @mbggenerated Fri Apr 27 22:28:05 CST 2018
     */
    Discounts selectByPrimaryKey(Integer disId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discounts
     *
     * @mbggenerated Fri Apr 27 22:28:05 CST 2018
     */
    int updateByPrimaryKeySelective(Discounts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discounts
     *
     * @mbggenerated Fri Apr 27 22:28:05 CST 2018
     */
    int updateByPrimaryKey(Discounts record);

	List<Discounts> findDiscountsList();
}