package www.zhizunbao.dto.manage;

import java.io.Serializable;

@SuppressWarnings("serial")
public class CarouselImg implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carousel_img.carousel_id
     *
     * @mbggenerated Sun Apr 15 19:05:34 CST 2018
     */
    private Integer carouselId;
    private String imgAlt;
    private String insureName;
    public String getInsureName() {
		return insureName;
	}

	public void setInsureName(String insureName) {
		this.insureName = insureName;
	}

	public String getImgAlt() {
		return imgAlt;
	}

	public void setImgAlt(String imgAlt) {
		this.imgAlt = imgAlt;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carousel_img.img_order
     *
     * @mbggenerated Sun Apr 15 19:05:34 CST 2018
     */
    private Integer imgOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carousel_img.img_id
     *
     * @mbggenerated Sun Apr 15 19:05:34 CST 2018
     */
    private Integer imgId;
    
    private String imgSrc;
    public String getImgSrc() {
		return imgSrc;
	}

	public void setImgSrc(String imgSrc) {
		this.imgSrc = imgSrc;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carousel_img.carousel_id
     *
     * @return the value of carousel_img.carousel_id
     *
     * @mbggenerated Sun Apr 15 19:05:34 CST 2018
     */
    public Integer getCarouselId() {
        return carouselId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carousel_img.carousel_id
     *
     * @param carouselId the value for carousel_img.carousel_id
     *
     * @mbggenerated Sun Apr 15 19:05:34 CST 2018
     */
    public void setCarouselId(Integer carouselId) {
        this.carouselId = carouselId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carousel_img.img_order
     *
     * @return the value of carousel_img.img_order
     *
     * @mbggenerated Sun Apr 15 19:05:34 CST 2018
     */
    public Integer getImgOrder() {
        return imgOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carousel_img.img_order
     *
     * @param imgOrder the value for carousel_img.img_order
     *
     * @mbggenerated Sun Apr 15 19:05:34 CST 2018
     */
    public void setImgOrder(Integer imgOrder) {
        this.imgOrder = imgOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carousel_img.img_id
     *
     * @return the value of carousel_img.img_id
     *
     * @mbggenerated Sun Apr 15 19:05:34 CST 2018
     */
    public Integer getImgId() {
        return imgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carousel_img.img_id
     *
     * @param imgId the value for carousel_img.img_id
     *
     * @mbggenerated Sun Apr 15 19:05:34 CST 2018
     */
    public void setImgId(Integer imgId) {
        this.imgId = imgId;
    }

	
    
}