package www.zhizunbao.dto.manage;

import java.util.Date;

public class Log {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.log_id
     *
     * @mbggenerated Fri Apr 27 21:04:54 CST 2018
     */
    private Integer logId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.user_name
     *
     * @mbggenerated Fri Apr 27 21:04:54 CST 2018
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.log_time
     *
     * @mbggenerated Fri Apr 27 21:04:54 CST 2018
     */
    private Date logTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.log_class
     *
     * @mbggenerated Fri Apr 27 21:04:54 CST 2018
     */
    private String logClass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.log_method
     *
     * @mbggenerated Fri Apr 27 21:04:54 CST 2018
     */
    private String logMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.log_level
     *
     * @mbggenerated Fri Apr 27 21:04:54 CST 2018
     */
    private String logLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.log_path
     *
     * @mbggenerated Fri Apr 27 21:04:54 CST 2018
     */
    private String logPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.log_msg
     *
     * @mbggenerated Fri Apr 27 21:04:54 CST 2018
     */
    private String logMsg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.log_id
     *
     * @return the value of log.log_id
     *
     * @mbggenerated Fri Apr 27 21:04:54 CST 2018
     */
    public Integer getLogId() {
        return logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.log_id
     *
     * @param logId the value for log.log_id
     *
     * @mbggenerated Fri Apr 27 21:04:54 CST 2018
     */
    public void setLogId(Integer logId) {
        this.logId = logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.user_name
     *
     * @return the value of log.user_name
     *
     * @mbggenerated Fri Apr 27 21:04:54 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.user_name
     *
     * @param userName the value for log.user_name
     *
     * @mbggenerated Fri Apr 27 21:04:54 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.log_time
     *
     * @return the value of log.log_time
     *
     * @mbggenerated Fri Apr 27 21:04:54 CST 2018
     */
    public Date getLogTime() {
        return logTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.log_time
     *
     * @param logTime the value for log.log_time
     *
     * @mbggenerated Fri Apr 27 21:04:54 CST 2018
     */
    public void setLogTime(Date logTime) {
        this.logTime = logTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.log_class
     *
     * @return the value of log.log_class
     *
     * @mbggenerated Fri Apr 27 21:04:54 CST 2018
     */
    public String getLogClass() {
        return logClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.log_class
     *
     * @param logClass the value for log.log_class
     *
     * @mbggenerated Fri Apr 27 21:04:54 CST 2018
     */
    public void setLogClass(String logClass) {
        this.logClass = logClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.log_method
     *
     * @return the value of log.log_method
     *
     * @mbggenerated Fri Apr 27 21:04:54 CST 2018
     */
    public String getLogMethod() {
        return logMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.log_method
     *
     * @param logMethod the value for log.log_method
     *
     * @mbggenerated Fri Apr 27 21:04:54 CST 2018
     */
    public void setLogMethod(String logMethod) {
        this.logMethod = logMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.log_level
     *
     * @return the value of log.log_level
     *
     * @mbggenerated Fri Apr 27 21:04:54 CST 2018
     */
    public String getLogLevel() {
        return logLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.log_level
     *
     * @param logLevel the value for log.log_level
     *
     * @mbggenerated Fri Apr 27 21:04:54 CST 2018
     */
    public void setLogLevel(String logLevel) {
        this.logLevel = logLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.log_path
     *
     * @return the value of log.log_path
     *
     * @mbggenerated Fri Apr 27 21:04:54 CST 2018
     */
    public String getLogPath() {
        return logPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.log_path
     *
     * @param logPath the value for log.log_path
     *
     * @mbggenerated Fri Apr 27 21:04:54 CST 2018
     */
    public void setLogPath(String logPath) {
        this.logPath = logPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.log_msg
     *
     * @return the value of log.log_msg
     *
     * @mbggenerated Fri Apr 27 21:04:54 CST 2018
     */
    public String getLogMsg() {
        return logMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.log_msg
     *
     * @param logMsg the value for log.log_msg
     *
     * @mbggenerated Fri Apr 27 21:04:54 CST 2018
     */
    public void setLogMsg(String logMsg) {
        this.logMsg = logMsg;
    }
}