package www.zhizunbao.dto.manage;

import java.io.Serializable;

@SuppressWarnings("serial")
public class ManageRole implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_role_rel.id
     *
     * @mbggenerated Sun Apr 15 19:00:39 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_role_rel.manage_id
     *
     * @mbggenerated Sun Apr 15 19:00:39 CST 2018
     */
    private Integer manageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_role_rel.role_id
     *
     * @mbggenerated Sun Apr 15 19:00:39 CST 2018
     */
    private Integer roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_role_rel.id
     *
     * @return the value of manage_role_rel.id
     *
     * @mbggenerated Sun Apr 15 19:00:39 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_role_rel.id
     *
     * @param id the value for manage_role_rel.id
     *
     * @mbggenerated Sun Apr 15 19:00:39 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_role_rel.manage_id
     *
     * @return the value of manage_role_rel.manage_id
     *
     * @mbggenerated Sun Apr 15 19:00:39 CST 2018
     */
    public Integer getManageId() {
        return manageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_role_rel.manage_id
     *
     * @param manageId the value for manage_role_rel.manage_id
     *
     * @mbggenerated Sun Apr 15 19:00:39 CST 2018
     */
    public void setManageId(Integer manageId) {
        this.manageId = manageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_role_rel.role_id
     *
     * @return the value of manage_role_rel.role_id
     *
     * @mbggenerated Sun Apr 15 19:00:39 CST 2018
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_role_rel.role_id
     *
     * @param roleId the value for manage_role_rel.role_id
     *
     * @mbggenerated Sun Apr 15 19:00:39 CST 2018
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
}