package www.zhizunbao.mapper.manage;

import java.util.List;

import www.zhizunbao.dto.manage.Manage;

public interface ManageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage
     *
     * @mbggenerated Thu Apr 19 19:12:45 CST 2018
     */
    int deleteByPrimaryKey(Integer manageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage
     *
     * @mbggenerated Thu Apr 19 19:12:45 CST 2018
     */
    int insert(Manage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage
     *
     * @mbggenerated Thu Apr 19 19:12:45 CST 2018
     */
    int insertSelective(Manage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage
     *
     * @mbggenerated Thu Apr 19 19:12:45 CST 2018
     */
    Manage selectByPrimaryKey(Integer manageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage
     *
     * @mbggenerated Thu Apr 19 19:12:45 CST 2018
     */
    int updateByPrimaryKeySelective(Manage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manage
     *
     * @mbggenerated Thu Apr 19 19:12:45 CST 2018
     */
    int updateByPrimaryKey(Manage record);
    
    List<Manage> findManage(Manage manage);

	Integer updateStatus(Manage manage);

	Integer updateManage(Manage manage);

	Manage login(String username);

	Manage findRoleNameByManage(Integer manageId);

	void uptadeByMLogin(Manage manage);

	void uptadeSteMLogin(Integer manageId);

	int updateManageLogin(Manage man);

	int updateLoginNumber(Manage man);

}