package www.zhizunbao.mapper.manage;

import www.zhizunbao.dto.manage.CommentOption;

public interface CommentOptionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_option
     *
     * @mbggenerated Sun Apr 15 19:07:03 CST 2018
     */
    int deleteByPrimaryKey(Integer optionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_option
     *
     * @mbggenerated Sun Apr 15 19:07:03 CST 2018
     */
    int insert(CommentOption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_option
     *
     * @mbggenerated Sun Apr 15 19:07:03 CST 2018
     */
    int insertSelective(CommentOption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_option
     *
     * @mbggenerated Sun Apr 15 19:07:03 CST 2018
     */
    CommentOption selectByPrimaryKey(Integer optionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_option
     *
     * @mbggenerated Sun Apr 15 19:07:03 CST 2018
     */
    int updateByPrimaryKeySelective(CommentOption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_option
     *
     * @mbggenerated Sun Apr 15 19:07:03 CST 2018
     */
    int updateByPrimaryKey(CommentOption record);
}