package www.zhizunbao.mapper.claim;

import java.util.List;

import www.zhizunbao.dto.claim.ClaimRule;

public interface ClaimRuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table claim_rule
     *
     * @mbggenerated Sun Apr 15 19:03:17 CST 2018
     */
    int deleteByPrimaryKey(Integer claimId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table claim_rule
     *
     * @mbggenerated Sun Apr 15 19:03:17 CST 2018
     */
    int insert(ClaimRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table claim_rule
     *
     * @mbggenerated Sun Apr 15 19:03:17 CST 2018
     */
    int insertSelective(ClaimRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table claim_rule
     *
     * @mbggenerated Sun Apr 15 19:03:17 CST 2018
     */
    List<ClaimRule> selectByPrimaryKey();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table claim_rule
     *
     * @mbggenerated Sun Apr 15 19:03:17 CST 2018
     */
    int updateByPrimaryKeySelective(ClaimRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table claim_rule
     *
     * @mbggenerated Sun Apr 15 19:03:17 CST 2018
     */
    int updateByPrimaryKey(ClaimRule record);
}