package www.zhizunbao.dto.manage;

import java.io.Serializable;

@SuppressWarnings("serial")
public class RoleResources implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_res_rel.id
     *
     * @mbggenerated Sun Apr 15 19:01:26 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_res_rel.role_id
     *
     * @mbggenerated Sun Apr 15 19:01:26 CST 2018
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_res_rel.res_id
     *
     * @mbggenerated Sun Apr 15 19:01:26 CST 2018
     */
    private Integer resId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_res_rel.id
     *
     * @return the value of role_res_rel.id
     *
     * @mbggenerated Sun Apr 15 19:01:26 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_res_rel.id
     *
     * @param id the value for role_res_rel.id
     *
     * @mbggenerated Sun Apr 15 19:01:26 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_res_rel.role_id
     *
     * @return the value of role_res_rel.role_id
     *
     * @mbggenerated Sun Apr 15 19:01:26 CST 2018
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_res_rel.role_id
     *
     * @param roleId the value for role_res_rel.role_id
     *
     * @mbggenerated Sun Apr 15 19:01:26 CST 2018
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_res_rel.res_id
     *
     * @return the value of role_res_rel.res_id
     *
     * @mbggenerated Sun Apr 15 19:01:26 CST 2018
     */
    public Integer getResId() {
        return resId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_res_rel.res_id
     *
     * @param resId the value for role_res_rel.res_id
     *
     * @mbggenerated Sun Apr 15 19:01:26 CST 2018
     */
    public void setResId(Integer resId) {
        this.resId = resId;
    }

	public RoleResources() {
		super();
		// TODO Auto-generated constructor stub
	}

	public RoleResources(Integer id, Integer roleId, Integer resId) {
		super();
		this.id = id;
		this.roleId = roleId;
		this.resId = resId;
	}

	@Override
	public String toString() {
		return "RoleResources [id=" + id + ", roleId=" + roleId + ", resId=" + resId + "]";
	}
    
}