package www.zhizunbao.mapper.manage;

import java.util.List;
import java.util.Map;

import www.zhizunbao.dto.manage.Resources;
import www.zhizunbao.dto.manage.RoleResources;

public interface RoleResourcesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_res_rel
     *
     * @mbggenerated Sun Apr 15 19:01:26 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_res_rel
     *
     * @mbggenerated Sun Apr 15 19:01:26 CST 2018
     */
    int insert(RoleResources record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_res_rel
     *
     * @mbggenerated Sun Apr 15 19:01:26 CST 2018
     */
    int insertSelective(RoleResources record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_res_rel
     *
     * @mbggenerated Sun Apr 15 19:01:26 CST 2018
     */
    RoleResources selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_res_rel
     *
     * @mbggenerated Sun Apr 15 19:01:26 CST 2018
     */
    int updateByPrimaryKeySelective(RoleResources record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_res_rel
     *
     * @mbggenerated Sun Apr 15 19:01:26 CST 2018
     */
    int updateByPrimaryKey(RoleResources record);

	int insertResourcesByRoleId(Map<String, Object> map);

	
}