package www.zhizunbao.mapper.manage;

import www.zhizunbao.dto.manage.UserCollect;

public interface UserCollectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_collect
     *
     * @mbggenerated Sun Apr 15 19:08:01 CST 2018
     */
    int deleteByPrimaryKey(Integer collectId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_collect
     *
     * @mbggenerated Sun Apr 15 19:08:01 CST 2018
     */
    int insert(UserCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_collect
     *
     * @mbggenerated Sun Apr 15 19:08:01 CST 2018
     */
    int insertSelective(UserCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_collect
     *
     * @mbggenerated Sun Apr 15 19:08:01 CST 2018
     */
    UserCollect selectByPrimaryKey(Integer collectId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_collect
     *
     * @mbggenerated Sun Apr 15 19:08:01 CST 2018
     */
    int updateByPrimaryKeySelective(UserCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_collect
     *
     * @mbggenerated Sun Apr 15 19:08:01 CST 2018
     */
    int updateByPrimaryKey(UserCollect record);
}