package www.zhizunbao.dto.activity;

import java.io.Serializable;
import java.util.Date;

@SuppressWarnings("serial")
public class UserReadRel implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_read_rel.id
     *
     * @mbggenerated Sun Apr 15 18:56:13 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_read_rel.user_id
     *
     * @mbggenerated Sun Apr 15 18:56:13 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_read_rel.read_id
     *
     * @mbggenerated Sun Apr 15 18:56:13 CST 2018
     */
    private Integer readId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_read_rel.in_time
     *
     * @mbggenerated Sun Apr 15 18:56:13 CST 2018
     */
    private String inTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_read_rel.out_time
     *
     * @mbggenerated Sun Apr 15 18:56:13 CST 2018
     */
    private String outTime;
    
    
    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public Integer getReadId() {
        return readId;
    }

    public void setReadId(Integer readId) {
        this.readId = readId;
    }

	public String getInTime() {
		return inTime;
	}

	public void setInTime(String inTime) {
		this.inTime = inTime;
	}

	public String getOutTime() {
		return outTime;
	}

	public void setOutTime(String outTime) {
		this.outTime = outTime;
	}

}