package www.zhizunbao.mapper.insure;

import java.util.List;
import java.util.Map;

import www.zhizunbao.dto.insure.Comment;
import www.zhizunbao.dto.insure.InsureComment;

public interface CommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbggenerated Sun Apr 15 19:22:56 CST 2018
     */
    int deleteByPrimaryKey(Integer commentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbggenerated Sun Apr 15 19:22:56 CST 2018
     */
    int insert(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbggenerated Sun Apr 15 19:22:56 CST 2018
     */
    int insertSelective(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbggenerated Sun Apr 15 19:22:56 CST 2018
     */
    List<Comment> selectByPrimaryKey();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbggenerated Sun Apr 15 19:22:56 CST 2018
     */
    int updateByPrimaryKeySelective(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbggenerated Sun Apr 15 19:22:56 CST 2018
     */
    int updateByPrimaryKey(Comment record);

	List<Comment> findOne(Integer insureId);

	List<InsureComment> findCommentById(int id);

	int findCommentCountByInsureId(Integer insureId);

	List<Comment> findCommentLimit(Map<String, Object> map);
}