package www.zhizunbao.mapper.insure;

import java.util.List;
import java.util.Map;

import www.zhizunbao.dto.insure.InsureFeature;

public interface InsureFeatureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table insure_feature_rel
     *
     * @mbggenerated Sun Apr 15 19:21:06 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table insure_feature_rel
     *
     * @mbggenerated Sun Apr 15 19:21:06 CST 2018
     */
    int insert(InsureFeature record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table insure_feature_rel
     *
     * @mbggenerated Sun Apr 15 19:21:06 CST 2018
     */
    int insertSelective(InsureFeature record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table insure_feature_rel
     *
     * @mbggenerated Sun Apr 15 19:21:06 CST 2018
     */
    InsureFeature selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table insure_feature_rel
     *
     * @mbggenerated Sun Apr 15 19:21:06 CST 2018
     */
    int updateByPrimaryKeySelective(InsureFeature record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table insure_feature_rel
     *
     * @mbggenerated Sun Apr 15 19:21:06 CST 2018
     */
    int updateByPrimaryKey(InsureFeature record);

	void insertAll(Map<String, Object> map);

	List<InsureFeature> findInsureFeatureByInsureId(Integer insureId);

	void deleteByInsureId(Integer insureId);
}