package www.zhizunbao.mapper.insure;

import www.zhizunbao.dto.insure.InsureShape;

public interface InsureShapeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table insure_shape_rel
     *
     * @mbggenerated Sun Apr 15 19:18:55 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table insure_shape_rel
     *
     * @mbggenerated Sun Apr 15 19:18:55 CST 2018
     */
    int insert(InsureShape record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table insure_shape_rel
     *
     * @mbggenerated Sun Apr 15 19:18:55 CST 2018
     */
    int insertSelective(InsureShape record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table insure_shape_rel
     *
     * @mbggenerated Sun Apr 15 19:18:55 CST 2018
     */
    InsureShape selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table insure_shape_rel
     *
     * @mbggenerated Sun Apr 15 19:18:55 CST 2018
     */
    int updateByPrimaryKeySelective(InsureShape record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table insure_shape_rel
     *
     * @mbggenerated Sun Apr 15 19:18:55 CST 2018
     */
    int updateByPrimaryKey(InsureShape record);
}