package www.zhizunbao.mapper.insure;

import www.zhizunbao.dto.insure.UserInsure;

public interface UserInsureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_insure_rel
     *
     * @mbggenerated Tue Apr 24 12:55:39 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_insure_rel
     *
     * @mbggenerated Tue Apr 24 12:55:39 CST 2018
     */
    int insert(UserInsure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_insure_rel
     *
     * @mbggenerated Tue Apr 24 12:55:39 CST 2018
     */
    int insertSelective(UserInsure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_insure_rel
     *
     * @mbggenerated Tue Apr 24 12:55:39 CST 2018
     */
    UserInsure selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_insure_rel
     *
     * @mbggenerated Tue Apr 24 12:55:39 CST 2018
     */
    int updateByPrimaryKeySelective(UserInsure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_insure_rel
     *
     * @mbggenerated Tue Apr 24 12:55:39 CST 2018
     */
    int updateByPrimaryKey(UserInsure record);

	int updateByOrderIdSelective(UserInsure userInsure);
}