package www.zhizunbao.dto.activity;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

import www.zhizunbao.dto.manage.UserInfo;

@SuppressWarnings("serial")
public class UserRead implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_read.read_id
     *
     * @mbggenerated Sun Apr 15 18:56:39 CST 2018
     */
    private Integer readId;
    private List<UserInfo> ulist;
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_read_rel.user_id
     *
     * @mbggenerated Sun Apr 15 18:56:13 CST 2018
     */
    private Integer userId;
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_read_rel.read_id
     *
     * @mbggenerated Sun Apr 15 18:56:13 CST 2018
     */


    public List<UserInfo> getUlist() {
		return ulist;
	}

	public void setUlist(List<UserInfo> ulist) {
		this.ulist = ulist;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getUserId() {
		return userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getInTime() {
		return inTime;
	}

	public void setInTime(String inTime) {
		this.inTime = inTime;
	}

	public String getOutTime() {
		return outTime;
	}

	public void setOutTime(String outTime) {
		this.outTime = outTime;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_read_rel.in_time
     *
     * @mbggenerated Sun Apr 15 18:56:13 CST 2018
     */
    private String inTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_read_rel.out_time
     *
     * @mbggenerated Sun Apr 15 18:56:13 CST 2018
     */
    private String outTime;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_read.read_title
     *
     * @mbggenerated Sun Apr 15 18:56:39 CST 2018
     */
    private String readTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_read.read_img
     *
     * @mbggenerated Sun Apr 15 18:56:39 CST 2018
     */
    private String readImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_read.read_content
     *
     * @mbggenerated Sun Apr 15 18:56:39 CST 2018
     */
    private String readContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_read.read_order
     *
     * @mbggenerated Sun Apr 15 18:56:39 CST 2018
     */
    private Integer readOrder;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_read.read_id
     *
     * @return the value of user_read.read_id
     *
     * @mbggenerated Sun Apr 15 18:56:39 CST 2018
     */
    public Integer getReadId() {
        return readId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_read.read_id
     *
     * @param readId the value for user_read.read_id
     *
     * @mbggenerated Sun Apr 15 18:56:39 CST 2018
     */
    public void setReadId(Integer readId) {
        this.readId = readId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_read.read_title
     *
     * @return the value of user_read.read_title
     *
     * @mbggenerated Sun Apr 15 18:56:39 CST 2018
     */
    public String getReadTitle() {
        return readTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_read.read_title
     *
     * @param readTitle the value for user_read.read_title
     *
     * @mbggenerated Sun Apr 15 18:56:39 CST 2018
     */
    public void setReadTitle(String readTitle) {
        this.readTitle = readTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_read.read_img
     *
     * @return the value of user_read.read_img
     *
     * @mbggenerated Sun Apr 15 18:56:39 CST 2018
     */
    public String getReadImg() {
        return readImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_read.read_img
     *
     * @param readImg the value for user_read.read_img
     *
     * @mbggenerated Sun Apr 15 18:56:39 CST 2018
     */
    public void setReadImg(String readImg) {
        this.readImg = readImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_read.read_content
     *
     * @return the value of user_read.read_content
     *
     * @mbggenerated Sun Apr 15 18:56:39 CST 2018
     */
    public String getReadContent() {
        return readContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_read.read_content
     *
     * @param readContent the value for user_read.read_content
     *
     * @mbggenerated Sun Apr 15 18:56:39 CST 2018
     */
    public void setReadContent(String readContent) {
        this.readContent = readContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_read.read_order
     *
     * @return the value of user_read.read_order
     *
     * @mbggenerated Sun Apr 15 18:56:39 CST 2018
     */
    public Integer getReadOrder() {
        return readOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_read.read_order
     *
     * @param readOrder the value for user_read.read_order
     *
     * @mbggenerated Sun Apr 15 18:56:39 CST 2018
     */
    public void setReadOrder(Integer readOrder) {
        this.readOrder = readOrder;
    }
}